import { dirname } from 'path'
import { fileURLToPath } from 'url'
import { FlatCompat } from '@eslint/eslintrc'

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) })

const config = [
  // next-env.d.ts is generated by the framework on every build, so linting it
  // only ever produces noise nobody is allowed to fix.
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'drizzle/**',
      'next-env.d.ts',
      // Vendored design-tool output, not our source. It ships its own bundled
      // React and is read as a reference, never built or imported.
      'design_handoff_maharaja_tofu/**',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
]

export default config
